# Generated by Django 2.1.3 on 2019-01-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceniarka', '0002_auto_20190102_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kont', models.BigIntegerField(null=None)),
                ('temat', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'kontrola_tematy',
                'managed': False,
            },
        ),
    ]
