# Generated by Django 2.1.3 on 2019-01-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceniarka', '0003_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kont', models.BigIntegerField(null=None)),
                ('nr_tematu', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'kontrola_tematy',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='control',
            table='kontrole',
        ),
    ]
