# Generated by Django 2.1.3 on 2019-01-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceniarka', '0004_auto_20190114_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='control_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
