# Generated by Django 2.1.3 on 2019-01-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceniarka', '0005_document_control_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=254)),
                ('email_to', models.EmailField(max_length=254)),
                ('email_message', models.TextField()),
            ],
        ),
    ]
