# Generated by Django 2.1.3 on 2019-01-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceniarka', '0006_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='control_number',
            field=models.CharField(default='xxxx', max_length=4),
            preserve_default=False,
        ),
    ]
